# Generated by Django 5.1.3 on 2024-12-03 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "employee_department",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmployeeSystemconfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_days_per_month", models.IntegerField(blank=True, null=True)),
                ("late_deduction_rate", models.FloatField(blank=True, null=True)),
                (
                    "early_leave_deduction_rate",
                    models.FloatField(blank=True, null=True),
                ),
                ("leave_deduction_rate", models.FloatField(blank=True, null=True)),
                ("overtime_bonus_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee_systemconfig",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmployeeEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.employeedepartment",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subordinates",
                        to="employee.employeeemployee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_employee",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("late_days", models.IntegerField(blank=True, null=True)),
                ("early_leave_days", models.IntegerField(blank=True, null=True)),
                ("leave_days", models.IntegerField(blank=True, null=True)),
                ("overtime_hours", models.FloatField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.employeedepartment",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.employeeemployee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_attendance",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("base_salary", models.FloatField(blank=True, null=True)),
                ("housing_allowance", models.FloatField(blank=True, null=True)),
                ("gross_salary", models.FloatField(blank=True, null=True)),
                ("deductions", models.FloatField(blank=True, null=True)),
                ("net_salary", models.FloatField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.employeedepartment",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employee.employeeemployee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_salary",
                "managed": True,
            },
        ),
    ]
